from PySide2 import QtCore, QtGui, QtWidgets

class Ui_XYZToolUi(object):
    def setupUi(self, XYZToolUi):
        XYZToolUi.setObjectName("XYZToolUi")
        XYZToolUi.resize(625, 204)
        self.gridLayout = QtWidgets.QGridLayout(XYZToolUi)
        self.gridLayout.setObjectName("gridLayout")
        self.setup = QtWidgets.QPushButton(XYZToolUi)
        self.setup.setObjectName("setup")
        self.gridLayout.addWidget(self.setup, 2, 0, 1, 1)
        self.line = QtWidgets.QFrame(XYZToolUi)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(XYZToolUi)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.RenderEngine = QtWidgets.QComboBox(XYZToolUi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RenderEngine.sizePolicy().hasHeightForWidth())
        self.RenderEngine.setSizePolicy(sizePolicy)
        self.RenderEngine.setObjectName("RenderEngine")
        self.RenderEngine.addItem("")
        self.RenderEngine.addItem("")
        self.RenderEngine.addItem("")
        self.horizontalLayout.addWidget(self.RenderEngine)
        self.keepShader = QtWidgets.QCheckBox(XYZToolUi)
        self.keepShader.setObjectName("keepShader")
        self.horizontalLayout.addWidget(self.keepShader)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(XYZToolUi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.pickMesh = QtWidgets.QPushButton(XYZToolUi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickMesh.sizePolicy().hasHeightForWidth())
        self.pickMesh.setSizePolicy(sizePolicy)
        self.pickMesh.setObjectName("pickMesh")
        self.horizontalLayout_5.addWidget(self.pickMesh)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_4 = QtWidgets.QLabel(XYZToolUi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_13.addWidget(self.label_4)
        self.udimFDM = QtWidgets.QCheckBox(XYZToolUi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.udimFDM.sizePolicy().hasHeightForWidth())
        self.udimFDM.setSizePolicy(sizePolicy)
        self.udimFDM.setObjectName("udimFDM")
        self.horizontalLayout_13.addWidget(self.udimFDM)
        self.pickFDM = QtWidgets.QPushButton(XYZToolUi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickFDM.sizePolicy().hasHeightForWidth())
        self.pickFDM.setSizePolicy(sizePolicy)
        self.pickFDM.setObjectName("pickFDM")
        self.horizontalLayout_13.addWidget(self.pickFDM)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_6 = QtWidgets.QLabel(XYZToolUi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_14.addWidget(self.label_6)
        self.udimXYZ = QtWidgets.QCheckBox(XYZToolUi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.udimXYZ.sizePolicy().hasHeightForWidth())
        self.udimXYZ.setSizePolicy(sizePolicy)
        self.udimXYZ.setObjectName("udimXYZ")
        self.horizontalLayout_14.addWidget(self.udimXYZ)
        self.pickXYZ = QtWidgets.QPushButton(XYZToolUi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickXYZ.sizePolicy().hasHeightForWidth())
        self.pickXYZ.setSizePolicy(sizePolicy)
        self.pickXYZ.setObjectName("pickXYZ")
        self.horizontalLayout_14.addWidget(self.pickXYZ)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(XYZToolUi)
        QtCore.QMetaObject.connectSlotsByName(XYZToolUi)

    def retranslateUi(self, XYZToolUi):
        XYZToolUi.setWindowTitle(QtWidgets.QApplication.translate("XYZToolUi", "XYZ Displacement Tool", None, -1))
        self.setup.setText(QtWidgets.QApplication.translate("XYZToolUi", "Set it up", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("XYZToolUi", "Render Engine........................................", None, -1))
        self.RenderEngine.setItemText(0, QtWidgets.QApplication.translate("XYZToolUi", "Arnold", None, -1))
        self.RenderEngine.setItemText(1, QtWidgets.QApplication.translate("XYZToolUi", "Renderman", None, -1))
        self.RenderEngine.setItemText(2, QtWidgets.QApplication.translate("XYZToolUi", "Vray", None, -1))
        self.keepShader.setText(QtWidgets.QApplication.translate("XYZToolUi", "keep current shader", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("XYZToolUi", "Mesh........................................................", None, -1))
        self.pickMesh.setText(QtWidgets.QApplication.translate("XYZToolUi", "pick", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("XYZToolUi", "Float Displacement Map.....", None, -1))
        self.udimFDM.setText(QtWidgets.QApplication.translate("XYZToolUi", "UDIM", None, -1))
        self.pickFDM.setText(QtWidgets.QApplication.translate("XYZToolUi", "pick", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("XYZToolUi", "XYZ Displacement Map........", None, -1))
        self.udimXYZ.setText(QtWidgets.QApplication.translate("XYZToolUi", "UDIM", None, -1))
        self.pickXYZ.setText(QtWidgets.QApplication.translate("XYZToolUi", "pick", None, -1))

